# -*- coding: utf-8 -*-
"""2. 학생 성적 관리 class

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jcngAZxbg7AvXTHVJYdWN-BNXfe5JdkK
"""

class Student_grades:
  def __init__(self, korean, english, math, name):
    self.__korean = korean
    self.__english = english
    self.__math = math
    self.__name = name
  
  def __mean_score(self):
    return (self.__korean + self.__english + self.__math)/3
  def __total_score(self):
    return self.__korean + self.__english + self.__math

mine = Student_grades(100,90,80, '황태규')