# -*- coding: utf-8 -*-
"""3. 피자 가게 관리 class

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Hk4n4T2yISW2syr2CdxLt6BjGUO_eybF
"""

class Pizza_store:
      
  def __init__(self, menu, name):
    self.__menu = menu
    self.__name = name
  def possible(self, want):
    if want in self.__menu :
      return 'YES'
    else :
      return 'NO'

my_store = Pizza_store(['슈퍼슈프림', '콤비네이션', '불고기'], '태규피자')

my_store.possible('슈퍼슈프림')

my_store.possible('포테이토')