# -*- coding: utf-8 -*-
"""1. 계좌 관리 class

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18Ln1KR2qGCGKq15QlL9CfN9lfa8h9AGT
"""

class Account:
  def __init__(self):
    self.__balance = 0


  def __withdraw(self, amount):
    self.__balance -= amount
    return self.__balance
  def __save(self, amount):
    self.__balance += amount
    return self.__balance
  def __check(self):
    return self.__balance
